--- list of all the modules in GuiH
-- @module modules
-- @see guih.lib.algo
-- @see guih.lib.blbfor
-- @see guih.lib.fuzzy_find
-- @see guih.lib.general
-- @see guih.lib.graphic
-- @see guih.lib.log
-- @see guih.lib.ppm
-- @see guih.lib.pixelbox
-- @see guih.lib.sevensh
-- @see guih.lib.termtools
-- @see guih.lib.text